name: ci
on:
  push:
  pull_request:

env:
  SATYSFI_VERSION: branch-dev-0-1-0-separate-saphe-from-satysfi

jobs:
  build-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          satysfi-version: ${{ env.SATYSFI_VERSION }}
      - run: git clone --branch ${{ env.SATYSFI_VERSION }} --depth 1 https://github.com/gfngfn/SATySFi.git
      - run: cd SATySFi/demo && saphe solve demo.saty && saphe build demo.saty
