name: ci
on:
  push:

jobs:
  build-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          satysfi-version: branch-dev-0-1-0-separate-saphe-from-satysfi
      - run: git clone --branch dev-0-1-0-separate-saphe-from-satysfi --depth 1 https://github.com/gfngfn/SATySFi.git
      - run: |
          cd SATySFi/demo
          saphe solve demo.saty
          saphe build demo.saty
